version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.14.1
      working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v -race ./...
  build:
    environment:
      IMAGE_NAME: albertwilliamsxyz/technical-exercise
    docker:
      - image: circleci/buildpack-deps:stretch
      working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            branches:
              only: 
              - master
              - dev
      - build:
          filters:
            branches:
              only:
              - master
