apiVersion: v1  
kind: Service      
metadata:
  name: technical-exercise-service
spec:
  type: NodePort
  selector:
    app: technical-exercise 
  ports: 
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
    nodePort: 30001
