// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package technical_exercise

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	FirstOperand         int32    `protobuf:"varint,1,opt,name=firstOperand,proto3" json:"firstOperand,omitempty"`
	SecondOperand        int32    `protobuf:"varint,2,opt,name=secondOperand,proto3" json:"secondOperand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetFirstOperand() int32 {
	if m != nil {
		return m.FirstOperand
	}
	return 0
}

func (m *AddRequest) GetSecondOperand() int32 {
	if m != nil {
		return m.SecondOperand
	}
	return 0
}

type AddResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "technical_exercise.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "technical_exercise.AddResponse")
}

func init() {
	proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784)
}

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2a, 0x49, 0x4d, 0xce, 0xc8,
	0xcb, 0x4c, 0x4e, 0xcc, 0x89, 0x4f, 0xad, 0x48, 0x2d, 0x4a, 0xce, 0x2c, 0x4e, 0x55, 0x0a, 0xe3,
	0xe2, 0x72, 0x4c, 0x49, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe2, 0xe2, 0x49,
	0xcb, 0x2c, 0x2a, 0x2e, 0xf1, 0x2f, 0x48, 0x2d, 0x4a, 0xcc, 0x4b, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x42, 0x11, 0x13, 0x52, 0xe1, 0xe2, 0x2d, 0x4e, 0x4d, 0xce, 0xcf, 0x4b, 0x81, 0x29,
	0x62, 0x02, 0x2b, 0x42, 0x15, 0x54, 0x52, 0xe5, 0xe2, 0x06, 0x9b, 0x5b, 0x5c, 0x90, 0x9f, 0x57,
	0x9c, 0x2a, 0x24, 0xc6, 0xc5, 0x56, 0x94, 0x5a, 0x5c, 0x9a, 0x53, 0x02, 0x35, 0x12, 0xca, 0x33,
	0x4a, 0xe2, 0x92, 0x08, 0x81, 0x39, 0xca, 0x15, 0xea, 0xa6, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4,
	0x54, 0x21, 0x37, 0x2e, 0x66, 0xc7, 0x94, 0x14, 0x21, 0x39, 0x3d, 0x4c, 0x67, 0xeb, 0x21, 0xdc,
	0x2c, 0x25, 0x8f, 0x53, 0x1e, 0x62, 0x77, 0x12, 0x1b, 0xd8, 0xf7, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0x88, 0x55, 0xb1, 0x0e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TechnicalExerciseServiceClient is the client API for TechnicalExerciseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TechnicalExerciseServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type technicalExerciseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTechnicalExerciseServiceClient(cc grpc.ClientConnInterface) TechnicalExerciseServiceClient {
	return &technicalExerciseServiceClient{cc}
}

func (c *technicalExerciseServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/technical_exercise.TechnicalExerciseService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TechnicalExerciseServiceServer is the server API for TechnicalExerciseService service.
type TechnicalExerciseServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

// UnimplementedTechnicalExerciseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTechnicalExerciseServiceServer struct {
}

func (*UnimplementedTechnicalExerciseServiceServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterTechnicalExerciseServiceServer(s *grpc.Server, srv TechnicalExerciseServiceServer) {
	s.RegisterService(&_TechnicalExerciseService_serviceDesc, srv)
}

func _TechnicalExerciseService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalExerciseServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/technical_exercise.TechnicalExerciseService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalExerciseServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TechnicalExerciseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "technical_exercise.TechnicalExerciseService",
	HandlerType: (*TechnicalExerciseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TechnicalExerciseService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
